### ISSUE TITLE
[Bug] Undefined symbols after updating to v4.9.108

### ISSUE THREAD

**Issue by UweKeim** [darkreader/darkreader#14447]
### Prerequisites

- [x] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [x] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [x] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Using [Darkreader via NPM](https://www.npmjs.com/package/darkreader) in my own website as a JS file, I get these two errors:

> `Uncaught ReferenceError: __PLUS__ is not defined`

and

> `Uncaught TypeError: DarkReader.setFetchMethod is not a function`

The first one occurs in line 369:

<img width="401" height="178" alt="Image" src="https://github.com/user-attachments/assets/2782e5e7-e87a-4ea2-9892-f06f27df60d8" />

([See also in the source code of darkreader.js or darkreader.mjs in the NPM package](https://www.npmjs.com/package/darkreader?activeTab=code))

And the latter one occurs in my code when initializing Darkreader:

```html
<script>
        DarkReader.setFetchMethod(window.fetch);

        // Enable when the system color scheme is dark.
        DarkReader.auto({
                brightness: 100,
                contrast: 90,
                sepia: 10
        },
                { invert: ['img[src*=".svg"]'] });
</script>
```

This did not happen before v4.9.108.

### My question

Am I doing something wrong here?

### Website Address

https://qu.zeta-software.de

### Steps To Reproduce

1. Open the website
2. Look in the browser console
3. Discover the above errors

Also, the website does not get dark mode, since the errors occur.

### Expected Behavior

No errors, dark mode for the website.

### Actual Behavior

The above errors and no dark mode.

### Operating System

Windows

### Web Browser name and version

Google Chrome version 138.0.7204.97 (Offizieller Build) (64-Bit)

### Dark Reader version

v4.9.108

**Comment by cope** [comment]
Same here.
Duplicate of #14439 which has a bad title.

To me this looks like a build error, since the code where this comes from looks OK.

**Comment by alexanderby** [comment]
Please try `darkreader@4.9.109`.

**Comment by UweKeim** [comment]
Version 4.9.109 works again. Thank you, @alexanderby 🥰
